question_data = [
        {
            "type": "boolean",
            "difficulty": "easy",
            "category": "Entertainment: Video Games",
            "question": "In the game Dead by Daylight, the killer Michael Myers is refered to as &quot;The Shape&quot;.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "boolean",
            "difficulty": "medium",
            "category": "Science: Mathematics",
            "question": "The set of all algebraic numbers is countable.",
            "correct_answer": "True",
            "incorrect_answers": ["False"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Entertainment: Music",
            "question": "Which of these bands are NOT from Australia?",
            "correct_answer": "The Naked and Famous",
            "incorrect_answers": ["Cut Copy", "Empire of the Sun", "Tame Impala"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "History",
            "question": "Pol Pot was the former dictator of which country?",
            "correct_answer": "Cambodia",
            "incorrect_answers": ["Laos", "North Korea", "Vietnam"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "Science &amp; Nature",
            "question": "What is the largest animal currently on Earth?",
            "correct_answer": "Blue Whale",
            "incorrect_answers": ["Orca", "Colossal Squid", "Giraffe"],
        },
        {
            "type": "multiple",
            "difficulty": "easy",
            "category": "Entertainment: Video Games",
            "question": "In the Half-Life series, Gordon Freeman&#039;s signature weapon is a:",
            "correct_answer": "Crowbar",
            "incorrect_answers": ["Sledgehammer", "Fiber Wire", "Katana"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Entertainment: Film",
            "question": "What were the Chilled Monkey Brains made from during Indiana Jones and the Temple of Doom?",
            "correct_answer": "Custard and Raspberry Sauce",
            "incorrect_answers": [
                "Strawberry Ice Cream",
                "Cherry Yogurt",
                "Raspberry Sorbet",
            ],
        },
        {
            "type": "multiple",
            "difficulty": "hard",
            "category": "Entertainment: Music",
            "question": "Bj&ouml;rk&#039;s &quot;Unison&quot; contains a sample of which Oval song?",
            "correct_answer": "Aero Deck",
            "incorrect_answers": ["Textuell", "Panorama", "Do While"],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "History",
            "question": "Who was the leader of the Communist Party of Yugoslavia ?",
            "correct_answer": "Josip Broz Tito",
            "incorrect_answers": [
                "Karadjordje Petrovic",
                "Milos Obilic",
                "Aleskandar Petrovic",
            ],
        },
        {
            "type": "multiple",
            "difficulty": "medium",
            "category": "Geography",
            "question": "What is the name of the only remaining Grand Duchy in the world ?",
            "correct_answer": "Luxembourg",
            "incorrect_answers": ["Montenegro", "Liechtenstein", "Andorra"],
        },
    ]